# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2a60680b47c2762ab317acf0ab410eb94b581925e69b36e195d1165443faf91c6f2f0ed8a9d5a95e08e32b39bb584501104188f3c5f1a82f5a32a4157ba49d

test:
  secret_key_base: 7529c19392ee125ca5ac3e4ba2f8a58041eac87020ae6b0d35aba88ceab43cb0d030463b62f38dce92b3b2a4b350b21b442073cc2fedac3a23411b977e18db24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
